version: 2
updates:
  - package-ecosystem: npm
    directory: /packages/sdk
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /apps/backend
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /apps/frontend
    schedule:
      interval: monthly
